language: minimal

sudo: required

dist: xenial

services:
  - docker


before_install:
  - if [[ -n $(grep --exclude-dir=.git -I -P "\xa0" -r .) ]]; then echo 'NBSP characters found'; exit 1; fi
  - docker --version
  - sudo apt-get install -y --force-yes xfsprogs
  - sudo ./travis-builds/purge_cluster.sh
  - export RELEASE="travis-build-$TRAVIS_BRANCH-$TRAVIS_COMMIT"
  - sudo make RELEASE="$RELEASE" FLAVORS="${CEPH_FLAVOR},centos,7" build

install:
  - sudo ./travis-builds/prepare_osd_fs.sh
  - docker run -d --name ceph-demo -v /etc/modprobe.d:/etc/modprobe.d -e RGW_FRONTEND_TYPE="${RGW_FRONTEND_TYPE}" -e BLUESTORE_BLOCK_SIZE=15GB -e DEBUG=verbose -e RGW_FRONTEND_PORT=8000 -e MON_IP=127.0.0.1 -e CEPH_PUBLIC_NETWORK=0.0.0.0/0 -e CLUSTER=test -e CEPH_DEMO_UID=demo -e CEPH_DEMO_ACCESS_KEY=G1EZ5R4K6IJ7XUQKMAED -e CEPH_DEMO_SECRET_KEY=cNmUrqpBKjCMzcfqG8fg4Qk07Xkoyau52OmvnSsz -e CEPH_DEMO_BUCKET=foobar -e SREE_VERSION=v0.1 -e SREE_PORT=5001 -e DATA_TO_SYNC=/etc/modprobe.d -e DATA_TO_SYNC_BUCKET=travis ceph/daemon:"travis-build-$TRAVIS_BRANCH-$TRAVIS_COMMIT"-"${CEPH_FLAVOR}"-centos-7-x86_64 demo
  - sleep 5  # let's give the container 5sec to create its Ceph config file

script:
  - sudo ./travis-builds/validate_demo_cluster.sh
  - docker exec ceph-demo ps fauwwwx
  - docker exec ceph-demo ss -ntlp
  - docker exec ceph-demo cat /etc/ceph/test.conf
  # - curl -L https://github.com/ceph/cn/releases/download/v1.8.0/cn-v1.8.0-bb92a8e-linux-amd64 -o cn
  # - chmod +x cn
  # - ./cn cluster start "$RELEASE" -i ceph/daemon:"$RELEASE"-mimic-centos-7-x86_64


after_failure:
  - docker images
  - docker ps
  - docker ps -a
  - docker logs ceph-demo
  - docker exec ceph-demo ceph --cluster test -s

env:
  matrix:
    - CEPH_FLAVOR=nautilus RGW_FRONTEND_TYPE=beast