---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
    name: {{ .Values.storageclass.name }}
provisioner: kubernetes.io/rbd
parameters:
    monitors: {{ .Values.service.mon.name }}.{{ .Release.Namespace }}:{{ .Values.service.mon.port }}
    adminId: {{ .Values.storageclass.admin_id }}
    adminSecretName: {{ .Values.storageclass.admin_secret_name }}
    adminSecretNamespace: {{ .Release.Namespace }}
    pool: {{ .Values.storageclass.pool }}
    userId: {{ .Values.storageclass.user_id }}
    userSecretName: {{ .Values.storageclass.user_secret_name }}
