---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mon.name | quote }}
  labels:
    app: ceph
    daemon: mon
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  #https://github.com/ceph/ceph-docker/issues/573
spec:
  ports:
  - port: {{ .Values.service.mon.port }}
    protocol: TCP
    targetPort: {{ .Values.service.mon.port }}
  selector:
    app: ceph
    daemon: mon
    release: {{ .Release.Name }}
  clusterIP: None
