---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-mon
  namespace: ceph
spec:
  template:
    metadata:
      name: ceph-mon
      namespace: ceph
      labels:
        app: ceph
        daemon: mon
    spec:
      nodeSelector:
        node-type: storage
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: ceph-mon
          image: ceph/daemon:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
                exec:
                  # remove the mon on Pod stop.
                  command:
                    - "/remove-mon.sh"
          ports:
            - containerPort: 6789
          env:
            - name: CEPH_DAEMON
              value: MON
            - name: KV_TYPE
              value: k8s
            - name: NETWORK_AUTO_DETECT
              value: "4"
            - name: CLUSTER
              value: ceph
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
          livenessProbe:
              tcpSocket:
                port: 6789
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6789
              timeoutSeconds: 5
