---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  namespace: ceph
  labels:
    app: ceph
    daemon: rgw
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ceph
    daemon: rgw
  type: LoadBalancer
