---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ceph-osd
  namespace: ceph
  labels:
    app: ceph
    daemon: osd
spec:
  template:
    metadata:
      labels:
        app: ceph
        daemon: osd
    spec:
      nodeSelector:
        node-type: storage
      volumes:
        - name: devices
          hostPath:
            path: /dev
        - name: ceph
          emptyDir: {}
#          hostPath:
#            path: /opt/ceph
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
        - name: osd-directory
          emptyDir: {}
#          hostPath:
#            path: /home/core/data/ceph/osd
      containers:
        - name: osd-pod
          image: ceph/daemon:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: devices
              mountPath: /dev
            - name: ceph
              mountPath: /var/lib/ceph
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
            - name: osd-directory
              mountPath: /var/lib/ceph/osd
          securityContext:
            privileged: true
          env:
            - name: CEPH_DAEMON
              value: osd_directory
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
            - name: CEPH_GET_ADMIN_KEY
              value: "1"
          livenessProbe:
              tcpSocket:
                port: 6800
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6800
              timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
